In [1]:
#Name : Swaraj Ajay Datir
#Roll no. : 10
#Sec : C
#Subject : ET 2

# Creating Series

In [2]:
# Program for creating Series using series() method of Pandas Library

In [3]:
import pandas as pd

In [4]:
#Creating Student Name List
Name=["Deep","Ayush","Krishna","Swaraj","Soham","Tilak"]
Name

['Deep', 'Ayush', 'Krishna', 'Swaraj', 'Soham', 'Tilak']

In [5]:
#Creating a Series 
Roll_list=pd.Series(Name,index=[1,2,3,4,5,6])
print(Roll_list)

1       Deep
2      Ayush
3    Krishna
4     Swaraj
5      Soham
6      Tilak
dtype: object

# Creating Data Frame

In [6]:
#Import Pandas library
import pandas as pd

In [7]:
#Creating Data Frame
df=pd.DataFrame([[11,19,13,20],[11,18,15,21],[12,13,14,15]],
columns= ["SE","DSS","MLAI","SQl"])

In [8]:
df

   SE  DSS  MLAI  SQl
0  11   19    13   20
1  11   18    15   21
2  12   13    14   15

In [9]:
df.shape

(3, 4)

In [10]:
df.size

12

In [11]:
df.ndim

2

# Adding Record (Row) to the data frame

In [12]:
df2=pd.DataFrame([[5,6,7,8]],
columns= ["SE","DSS","MLAI","SQl"])

In [13]:

df3 = pd.concat([df, df2], ignore_index=True)

In [14]:
df3

   SE  DSS  MLAI  SQl
0  11   19    13   20
1  11   18    15   21
2  12   13    14   15
3   5    6     7    8

# Adding Attribute (Columns) name DM

In [15]:
df3["DM"]=[12,15,16,14]

In [16]:
df3

   SE  DSS  MLAI  SQl  DM
0  11   19    13   20  12
1  11   18    15   21  15
2  12   13    14   15  16
3   5    6     7    8  14

# Deleting Record from  df3 dataframe

In [17]:
df4=df3.drop(index=[1])

In [18]:
df4

   SE  DSS  MLAI  SQl  DM
0  11   19    13   20  12
2  12   13    14   15  16
3   5    6     7    8  14

# Deleting Attribute (Columns) from df3 dataframe

In [19]:
df5=df3.drop(columns=["DM"])

In [20]:
df5

   SE  DSS  MLAI  SQl
0  11   19    13   20
1  11   18    15   21
2  12   13    14   15
3   5    6     7    8

In [21]:
#Finding mean of DSS 

print("Mean of DSS:", df5["DSS"].mean())

Mean of DSS: 14.0

In [22]:
#Finding median of DSS

print("Median of DSS:", df5["DSS"].median())

Median of DSS: 15.5

In [23]:
#Finding mode of DSS

print("Mode of DSS:", df5["DSS"].mode())

Mode of DSS: 0     6
1    13
2    18
3    19
Name: DSS, dtype: int64

In [24]:
#Finding max number of DSS

print("Max of DSS:", df5["DSS"].max())

Max of DSS: 19

In [25]:
#Finding Min number of DSS

print("Max of DSS:", df5["DSS"].min())

Max of DSS: 6